### PR TITLE
Add Alpha Vantage mcp server

### PR DESCRIPTION
**Pull request by berlinbra**
Adds a new model context protocol to the README for the alpha vantage API.

### CODE REVIEW

**Review by SecretiveShell — COMMENTED** [review]
As Far as I can tell this is not a local server, it seems to rely on a cloud service.

**Comment by berlinbra** [comment]
@SecretiveShell It's a local server that makes queries to an API endpoint. Is there a different method you recommend? 
I was following the [official quickstart documentation](https://modelcontextprotocol.io/quickstart) which makes a similar api request

**Comment by punkpeye** [comment]
> @SecretiveShell It's a local server that makes queries to an API endpoint. Is there a different method you recommend? I was following the [official quickstart documentation](https://modelcontextprotocol.io/quickstart) which makes a similar api request

Local would be an MCP that is controlling software installed on the machine.

Network would be any remote API that the MCP server is talking to.

**Comment by punkpeye** [comment]
Added this context to the legend https://github.com/punkpeye/awesome-mcp-servers/blob/main/README.md#legend

**Comment by berlinbra** [comment]
Ah I see what you are saying, that makes sense. I've updated the PR to reflect the right icon. 
This one should probably be switched to Cloud as well, it uses a similar remote API request:
`[anjor/coinmarket-mcp-server](https://github.com/anjor/coinmarket-mcp-server) 🐍 🏠 - Coinmarket API integration to fetch cryptocurrency listings and quotes`

**Comment by punkpeye** [comment]
Thanks for flagging. Fixed in https://github.com/punkpeye/awesome-mcp-servers/commit/6546e87caa939d399e46fe2bff943a5bc47ceb53

**Pull request merged**
