### PR TITLE
Add langchain4j+quarkus to clients

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Comment by punkpeye** [comment]
What's the relationship to MCP?

**Comment by punkpeye** [comment]
Closing as seemingly unrelated.

**Comment by jmartisk** [comment]
@punkpeye, LangChain4j integrates a MCP client (to be precise, version 0.37.0 will)
See https://github.com/langchain4j/langchain4j/blob/main/docs/docs/tutorials/mcp.md

**Comment by jmartisk** [comment]
It's released as 1.0.0-alpha1 after all.
Quarkus is a platform that integrates LangChain4j and adds some stuff on top and is the recommended way to use LangChain4j. If you want, we could adjust the descriptions a bit.

**Comment by jmartisk** [comment]
Would changing the description for Langchain4j to `A Java framework for integrating LLMs that includes MCP client capabilities` work for you?

**Pull request closed without merging**
